global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

  external_labels:
    monitor: 'codelab-monitor'
    query_log_file: query_log_file.log

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: 'monitoring-item'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/asdf'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    params:
      user-id: ['myemail@email.com']

    static_configs:
      - targets: ['localhost:9090', 'localhost:9100', 'localhost:80']
        labels:
          service: 'monitor-1'
